### ISSUE TITLE
Aggregator functionality

### ISSUE THREAD

**Issue by JessedeDoes** [INL/clariah-fcs-endpoints#11]
Is still rather limited (cf. also issue about figuring out the status)

- Show metadata if a metadata dataview is included in results
- Metadata search
- Number of results
- Run and export complete query result (slow in fcs but possible)
- show translation of UD query to corpus-specific; if possible link to query execution in corpus (possible for blacklab-server-based corpora; also for Nederlab), so user can go there and tune query and do nicer things with the query results
- Kwic view highlights only first word of hit
- Advanced data view not readable

**Comment by pdekker12** [comment]
For now, we will use the aggregator as it is
